name: Betl
favicon: null
layout_spectrum: 0.2806505977641791
typography_spectrum: 0.16055756458081305
title: Betl mPOS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d2402b'
    - '#e98d20'
    - '#00721b'
    - '#77312a'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
